/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BookRouteImport } from './routes/book'
import { Route as BookDanceTeamRouteImport } from './routes/book-dance-team'
import { Route as BookUsRouteImport } from './routes/book-us'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CreativeDanceTeamRouteImport } from './routes/creative-dance-team'
import { Route as DanceRouteImport } from './routes/dance'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as EventsIndexRouteImport } from './routes/events.index'
import { Route as EventsSlugRouteImport } from './routes/events.$slug'
import { Route as TicketsTokenRouteImport } from './routes/tickets.$token'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const BookDanceTeamRoute = BookDanceTeamRouteImport.update({
  id: '/book-dance-team',
  path: '/book-dance-team',
  getParentRoute: () => rootRouteImport,
} as any)
const BookUsRoute = BookUsRouteImport.update({
  id: '/book-us',
  path: '/book-us',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CreativeDanceTeamRoute = CreativeDanceTeamRouteImport.update({
  id: '/creative-dance-team',
  path: '/creative-dance-team',
  getParentRoute: () => rootRouteImport,
} as any)
const DanceRoute = DanceRouteImport.update({
  id: '/dance',
  path: '/dance',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsSlugRoute = EventsSlugRouteImport.update({
  id: '/events/$slug',
  path: '/events/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketsTokenRoute = TicketsTokenRouteImport.update({
  id: '/tickets/$token',
  path: '/tickets/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/book': typeof BookRoute
  '/book-dance-team': typeof BookDanceTeamRoute
  '/book-us': typeof BookUsRoute
  '/contact': typeof ContactRoute
  '/creative-dance-team': typeof CreativeDanceTeamRoute
  '/dance': typeof DanceRoute
  '/gallery': typeof GalleryRoute
  '/services': typeof ServicesRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/events/$slug': typeof EventsSlugRoute
  '/tickets/$token': typeof TicketsTokenRoute
  '/events/': typeof EventsIndexRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/book': typeof BookRoute
  '/book-dance-team': typeof BookDanceTeamRoute
  '/book-us': typeof BookUsRoute
  '/contact': typeof ContactRoute
  '/creative-dance-team': typeof CreativeDanceTeamRoute
  '/dance': typeof DanceRoute
  '/gallery': typeof GalleryRoute
  '/services': typeof ServicesRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/events/$slug': typeof EventsSlugRoute
  '/tickets/$token': typeof TicketsTokenRoute
  '/events': typeof EventsIndexRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/book': typeof BookRoute
  '/book-dance-team': typeof BookDanceTeamRoute
  '/book-us': typeof BookUsRoute
  '/contact': typeof ContactRoute
  '/creative-dance-team': typeof CreativeDanceTeamRoute
  '/dance': typeof DanceRoute
  '/gallery': typeof GalleryRoute
  '/services': typeof ServicesRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/events/$slug': typeof EventsSlugRoute
  '/tickets/$token': typeof TicketsTokenRoute
  '/events/': typeof EventsIndexRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/book'
    | '/book-dance-team'
    | '/book-us'
    | '/contact'
    | '/creative-dance-team'
    | '/dance'
    | '/gallery'
    | '/services'
    | '/admin'
    | '/events/$slug'
    | '/tickets/$token'
    | '/events/'
    | '/api/public/payments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/book'
    | '/book-dance-team'
    | '/book-us'
    | '/contact'
    | '/creative-dance-team'
    | '/dance'
    | '/gallery'
    | '/services'
    | '/admin'
    | '/events/$slug'
    | '/tickets/$token'
    | '/events'
    | '/api/public/payments/webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/book'
    | '/book-dance-team'
    | '/book-us'
    | '/contact'
    | '/creative-dance-team'
    | '/dance'
    | '/gallery'
    | '/services'
    | '/_authenticated/admin'
    | '/events/$slug'
    | '/tickets/$token'
    | '/events/'
    | '/api/public/payments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  BookRoute: typeof BookRoute
  BookDanceTeamRoute: typeof BookDanceTeamRoute
  BookUsRoute: typeof BookUsRoute
  ContactRoute: typeof ContactRoute
  CreativeDanceTeamRoute: typeof CreativeDanceTeamRoute
  DanceRoute: typeof DanceRoute
  GalleryRoute: typeof GalleryRoute
  ServicesRoute: typeof ServicesRoute
  EventsSlugRoute: typeof EventsSlugRoute
  TicketsTokenRoute: typeof TicketsTokenRoute
  EventsIndexRoute: typeof EventsIndexRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book-dance-team': {
      id: '/book-dance-team'
      path: '/book-dance-team'
      fullPath: '/book-dance-team'
      preLoaderRoute: typeof BookDanceTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book-us': {
      id: '/book-us'
      path: '/book-us'
      fullPath: '/book-us'
      preLoaderRoute: typeof BookUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creative-dance-team': {
      id: '/creative-dance-team'
      path: '/creative-dance-team'
      fullPath: '/creative-dance-team'
      preLoaderRoute: typeof CreativeDanceTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dance': {
      id: '/dance'
      path: '/dance'
      fullPath: '/dance'
      preLoaderRoute: typeof DanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$slug': {
      id: '/events/$slug'
      path: '/events/$slug'
      fullPath: '/events/$slug'
      preLoaderRoute: typeof EventsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tickets/$token': {
      id: '/tickets/$token'
      path: '/tickets/$token'
      fullPath: '/tickets/$token'
      preLoaderRoute: typeof TicketsTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  BookRoute: BookRoute,
  BookDanceTeamRoute: BookDanceTeamRoute,
  BookUsRoute: BookUsRoute,
  ContactRoute: ContactRoute,
  CreativeDanceTeamRoute: CreativeDanceTeamRoute,
  DanceRoute: DanceRoute,
  GalleryRoute: GalleryRoute,
  ServicesRoute: ServicesRoute,
  EventsSlugRoute: EventsSlugRoute,
  TicketsTokenRoute: TicketsTokenRoute,
  EventsIndexRoute: EventsIndexRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
